spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/kob?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "Asia/Shanghai"
server:
  port: 3000
springdoc:
  swagger-ui:
    path: /doc.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: "Service Interface"
      packages-to-scan: com.celest.backend.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
backend:
  jwt:
    secret-key: 123456
    expire-time: 1296000000
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
